### ISSUE TITLE
Codes for figure1

### ISSUE THREAD

**Issue by YangWang92** [shenango/shenango#1]
Hi all,
Thanks for sharing such exciting work, and it inspires us a lot about resource allocation system design. As mentioned in section 2,  you build a simulator to evaluate the relationship between workload and CPU efficiency. Is it possible to share the source codes of this experiment? 

Thanks!
Yang

**Comment by joshuafried** [comment]
Hi Yang,

The code is here: https://github.com/shenango/bench/tree/master/simnet.

Best,
Josh
