### ISSUE TITLE
Legacy LLVM-style issue when building Rust bindings

### ISSUE THREAD

**Issue by andreybleme** [shenango/shenango#3]
Hi folks,

While building Shenango using Rust `1.52.0-nightly` release, I have faced the following issue:

![shenango_issue](https://user-images.githubusercontent.com/5385383/110560066-18cfa800-8124-11eb-876d-6d69f42ecb6f.png)

As for https://github.com/rust-lang/rust/issues/70173, https://doc.rust-lang.org/beta/unstable-book/library-features/llvm-asm.html, and the RFC https://github.com/rust-lang/rfcs/pull/2843 the old `asm` inline assembly  is deprecated (it was actually renamed). 

When replacing this with `llvm_asm!` and adding the crate attribute `#![feature(llvm_asm)]`, the build worked just fine ✅ 

I'll create a PR to address this. Let me know if it make sense to merge this indeed...

Thanks a lot for making Shenango available!

**Comment by aousterh** [comment]
Thanks! Resolved with commit fbc5978.

**Comment by piginthesettingsun** [comment]
Hi andreybleme, did you finally success to run the synthetic server? I got an error when I tried to start it.

**Comment by andreybleme** [comment]
Yes I did @piginthesettingsun . Let me know what's the error you're facing and I'll try to help you.

**Comment by piginthesettingsun** [comment]
I described the error in https://github.com/shenango/shenango/issues/6, we can discuss in that issue. Thanks for the help!
