### ISSUE TITLE
Failed to compile synthetic server

### ISSUE THREAD

**Issue by piginthesettingsun** [shenango/shenango#5]
I compiled Shenango's synthetic server in an environment with GCC 9.3.0 and GCC 7.3.0, Linux kernel 4.19 (a long-term version after 4.15), CentOS 7.9.
My clang version is 3.4.2, which caused the problem like https://github.com/RustAudio/coreaudio-sys/issues/18, and was solved as described above.
After solving the problem described in https://github.com/shenango/shenango/issues/3, I got a new error and failed to compile.
Have you ever seen this problem before, and do you have any advice?
Thank you!

my error log：
[root@localhost synthetic]# cargo build --release
   Compiling shenango v0.1.0 (/home/shenyifan/temp/shenango-master/bindings/rust)
warning: trait objects without an explicit `dyn` are deprecated
  --> /home/shenyifan/temp/shenango-master/bindings/rust/src/thread.rs:80:32
   |
80 |     data: Option<Result<T, Box<Any + Send + 'static>>>,
   |                                ^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Any + Send + 'static`
   |
   = note: `#[warn(bare_trait_objects)]` on by default

warning: trait objects without an explicit `dyn` are deprecated
  --> /home/shenyifan/temp/shenango-master/bindings/rust/src/thread.rs:97:44
   |
97 |     pub fn join(mut self) -> Result<T, Box<Any + Send + 'static>> {
   |                                            ^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Any + Send + 'static`

warning: use of deprecated function `std::mem::uninitialized`: use `mem::MaybeUninit` instead
   --> /home/shenyifan/temp/shenango-master/bindings/rust/src/lib.rs:101:55
    |
101 |         let inner = Arc::new(UnsafeCell::new(unsafe { std::mem::uninitialized() }));
    |                                                       ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: 3 warnings emitted

   Compiling synthetic v0.1.0 (/home/shenyifan/temp/shenango-master/apps/synthetic)
warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend.rs:276:40
    |
276 |     pub fn join(self) -> Result<T, Box<Any + Send + 'static>> {
    |                                        ^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Any + Send + 'static`
    |
    = note: `#[warn(bare_trait_objects)]` on by default

warning: unnecessary parentheses around block return value
   --> src/main.rs:147:5
    |
147 |     (duration.as_secs() * 1000_000_000 + duration.subsec_nanos() as u64)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses
    |
    = note: `#[warn(unused_parens)]` on by default

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/h
ome/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.0.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.1.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.10.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.11.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.12.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.13.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.14.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.15.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.2.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.3.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.4.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.5.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.6.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.7.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.8.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.9.rcgu.o" "-o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.1j80sxbtp18h99kd.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps" "-L" "../.." "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-a3b2353c72e89634.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-a76a7ffc0867499d.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-ba1c7bc534f87985.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-d0a3572205759673.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-716101092d4b23f1.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libshenango-d1554c8a5aeda4f4.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libnet2-64a34cfba41e4a4c.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libcfg_if-3dc8ad0d02b985d4.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libmersenne_twister-415fee4dfc788e91.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/librand-a6e97a696b1ccb48.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/liblockstep-20e0c4201487e8f5.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libhostname-0f33bb7b140ea132.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libdns_parser-d37be2c62080e3bc.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libquick_error-2c0af5e3e404a0cb.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libbyteorder-a7537bccfb17cf96.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libclap-d5843ffe54305800.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libvec_map-d4298544f133bf24.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libtextwrap-2dfb88fd0b109d84.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libunicode_width-e78bd6cfd8826c43.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libstrsim-08a9fdef8ac58cb9.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libbitflags-0f7e5f3e1adf4b08.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libatty-66dc26b7a40fbdfb.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/liblibc-c8963a5eec252695.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libansi_term-994abb4b74d18d9b.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-61556e43b375c2c0.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-787faa8b02fbd963.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-dda4c0b69607e93b.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-4b7dae8949ac132c.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-978e97832b309706.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-073b1b693304b876.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-c07f996a53ee6558.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-0ae8ed6a282247d0.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-978dd04958b6ebcc.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-14b94bdd9a47d665.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-bff7534e4dfcef6c.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-022f1a0e7cd794ec.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-ff456575f1773ef0.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-3aeb407930ebd519.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-6ab1ee6dbc17ad08.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-166dae07beec0398.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-761b290f47712921.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-T/../../../../../base/base.ld"  = note: /usr/bin/ld: /home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libshenango-d1554c8a5aeda4f4.rlib(time.o): relocation R_X86_64_32 against `.rodata.str1.1' can n
ot be used when making a shared object; recompile with -fPIC          /home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libshenango-d1554c8a5aeda4f4.rlib: could not read symbols: Bad value
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error; 2 warnings emitted

error: could not compile `synthetic`

To learn more, run the command again with --verbose.[root@localhost synthetic]# cargo build --release
   Compiling shenango v0.1.0 (/home/shenyifan/temp/shenango-master/bindings/rust)
warning: trait objects without an explicit `dyn` are deprecated
  --> /home/shenyifan/temp/shenango-master/bindings/rust/src/thread.rs:80:32
   |
80 |     data: Option<Result<T, Box<Any + Send + 'static>>>,
   |                                ^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Any + Send + 'static`
   |
   = note: `#[warn(bare_trait_objects)]` on by default

warning: trait objects without an explicit `dyn` are deprecated
  --> /home/shenyifan/temp/shenango-master/bindings/rust/src/thread.rs:97:44
   |
97 |     pub fn join(mut self) -> Result<T, Box<Any + Send + 'static>> {
   |                                            ^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Any + Send + 'static`

warning: use of deprecated function `std::mem::uninitialized`: use `mem::MaybeUninit` instead
   --> /home/shenyifan/temp/shenango-master/bindings/rust/src/lib.rs:101:55
    |
101 |         let inner = Arc::new(UnsafeCell::new(unsafe { std::mem::uninitialized() }));
    |                                                       ^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: 3 warnings emitted

   Compiling synthetic v0.1.0 (/home/shenyifan/temp/shenango-master/apps/synthetic)
warning: trait objects without an explicit `dyn` are deprecated
   --> src/backend.rs:276:40
    |
276 |     pub fn join(self) -> Result<T, Box<Any + Send + 'static>> {
    |                                        ^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn Any + Send + 'static`
    |
    = note: `#[warn(bare_trait_objects)]` on by default

warning: unnecessary parentheses around block return value
   --> src/main.rs:147:5
    |
147 |     (duration.as_secs() * 1000_000_000 + duration.subsec_nanos() as u64)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses
    |
    = note: `#[warn(unused_parens)]` on by default

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/h
ome/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.0.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.1.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.10.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.11.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.12.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.13.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.14.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.15.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.2.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.3.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.4.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.5.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.6.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.7.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.8.rcgu.o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.synthetic.750dtcy5-cgu.9.rcgu.o" "-o" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/synthetic-79a6a6de99c4f66f.1j80sxbtp18h99kd.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps" "-L" "../.." "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-a3b2353c72e89634.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-a76a7ffc0867499d.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-ba1c7bc534f87985.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-d0a3572205759673.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-716101092d4b23f1.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libshenango-d1554c8a5aeda4f4.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libnet2-64a34cfba41e4a4c.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libcfg_if-3dc8ad0d02b985d4.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libmersenne_twister-415fee4dfc788e91.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/librand-a6e97a696b1ccb48.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/liblockstep-20e0c4201487e8f5.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libhostname-0f33bb7b140ea132.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libdns_parser-d37be2c62080e3bc.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libquick_error-2c0af5e3e404a0cb.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libbyteorder-a7537bccfb17cf96.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libclap-d5843ffe54305800.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libvec_map-d4298544f133bf24.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libtextwrap-2dfb88fd0b109d84.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libunicode_width-e78bd6cfd8826c43.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libstrsim-08a9fdef8ac58cb9.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libbitflags-0f7e5f3e1adf4b08.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libatty-66dc26b7a40fbdfb.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/liblibc-c8963a5eec252695.rlib" "/home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libansi_term-994abb4b74d18d9b.rlib" "-Wl,--start-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-61556e43b375c2c0.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-787faa8b02fbd963.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-dda4c0b69607e93b.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-4b7dae8949ac132c.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-978e97832b309706.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-073b1b693304b876.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-c07f996a53ee6558.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-0ae8ed6a282247d0.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-978dd04958b6ebcc.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-14b94bdd9a47d665.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-bff7534e4dfcef6c.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-022f1a0e7cd794ec.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-ff456575f1773ef0.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-3aeb407930ebd519.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-6ab1ee6dbc17ad08.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-166dae07beec0398.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-761b290f47712921.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-T/../../../../../base/base.ld"  = note: /usr/bin/ld: /home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libshenango-d1554c8a5aeda4f4.rlib(time.o): relocation R_X86_64_32 against `.rodata.str1.1' can n
ot be used when making a shared object; recompile with -fPIC          /home/shenyifan/temp/shenango-master/apps/synthetic/target/release/deps/libshenango-d1554c8a5aeda4f4.rlib: could not read symbols: Bad value
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error; 2 warnings emitted

error: could not compile `synthetic`

To learn more, run the command again with --verbose.

**Comment by aousterh** [comment]
Thanks! Commit 6523859 should resolve these issues.
